version: '3.6'

services:
  nodeapi:
    build: .
    container_name: "nodeapi"
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: "mongodb"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"